config/routes.rb
Rails.application.routes.draw do
  # Redirect majestic seo bot to main page
  get '/ru/press-tsentr/novosti/v-rossii/prosmotr_novosti/-/:id', to: redirect('/404'), id: /.+http:\/ria\.ru\/nano_news\/20120222\/572000474\.html/

  devise_for :users, controllers: { invitations: 'manage/invitations' }

  devise_scope :user do
    get 'manage/invitations', to: 'manage/invitations#index'
  end

  namespace :manage do
    resource :user, only: [:edit, :update]
    resources :map_layers,  except: [:show]
    resources :placemarks,  except: [:index, :show]
    resources :permissions, except: [:show, :edit, :update]
    resources :events,      except: [:show]

    root to: 'map_layers#index'
  end

  namespace :workplace do
    resources :documents do
      get 'tags_list', on: :collection
      get 'participants_list', on: :collection
      get 'related_documents', on: :collection
    end

    resources :user_tags

    root to: 'documents#index'
  end

  get 'ru/inotomsk/ob-ekty'          => 'map_layers#index', :as => 'map_layers'
  get 'ru/dorozhnaya-karta'          => 'road_map#index',   :as => 'road_map'

  %w(
    peredovoe-proizvodstvo
    nauka-i-obrazovanie
    umnyy-i-udobnyy-gorod
    innovatsii-i-noviy-biznes
    delovaya-sreda
  ).each do |item|
    get "ru/#{item}" => 'directions#show', :defaults => { slug: item }, :as => item.underscore
  end

  %w(
    advanced-industry
    science-and-education
    technological-innovations-new-businesses
    smart-and-handy-city
    business-environment
  ).each do |item|
    get "en/#{item}" => 'directions#show', :defaults => { slug: item }, :as => item.underscore
  end

  # peredovoe proizvodsto
  %w(
    peredovoe-proizvodstvo/neftehimicheskiy-klaster
    peredovoe-proizvodstvo/klaster_yadernyh_tekhnologiy
    peredovoe-proizvodstvo/industrialnyy-park
    peredovoe-proizvodstvo/klaster-farmatsevtiki-medtehniki-i-it
    peredovoe-proizvodstvo/klaster-smart-technologiestomsk
    peredovoe-proizvodstvo/lesopromyshlennyy-klaster
    peredovoe-proizvodstvo/klaster-vozobnovlyaemyh-prirodnyh-resursov
    peredovoe-proizvodstvo/klaster-trudnoizvlekaemyh-prirod-resursov

    nauka-i-obrazovanie/nauchno-obrazovatelnyy-park
    nauka-i-obrazovanie/uchastie-v-federalnyh-initsiativah
    nauka-i-obrazovanie/tomskiy-natsionalnyy-issledovatelskiy-meditsinskiy-tsentr
    nauka-i-obrazovanie/detskiy-tehnopark-kvantorium
    nauka-i-obrazovanie/alyans-translyatsionnoy-meditsiny

    innovatsii-i-noviy-biznes/osobaya-ekonomicheskaya-zona
    innovatsii-i-noviy-biznes/poyas-innovatsionnyh-kompaniy

    umnyy-i-udobnyy-gorod/tomskaya-aglomeratsiya
    umnyy-i-udobnyy-gorod/tomskie-naberezhnye
    umnyy-i-udobnyy-gorod/meditsinskiy-park
    umnyy-i-udobnyy-gorod/istoriko-kulturnyy-park
    umnyy-i-udobnyy-gorod/sportivnyy-park
    umnyy-i-udobnyy-gorod/transportnaya-infrastruktura

  ).each do |item|
    get "ru/#{item}" => 'subdirections#show', :defaults => { slug: item.split('/').last }, :as => item.split('/').last.underscore
  end

  get 'en/road-map' => 'road_map#index'

  get 'files/:id/download' => 'workplace/documents#download', as: :download

  get '/(*path)', to: 'main#index'
  root to: 'main#index'
end

app/controllers/subdirections_controller.rb
class SubdirectionsController < MainController
  def show
    @map_layer = begin
                   MapLayer.find(params[:slug])
                 rescue
                   nil
                 end

    @placemarks = begin
                    MapLayer.find(params[:slug]).placemarks
                  rescue
                    nil
                  end
  end
end

app/views/subdirections/show.html.erb
<% content_for :content do %>
  <div class='content_wrapper index row directions_wrapper'>
    <div class="content_side col-lg-9 col-md-9 col-sm-8 col-xs-12 map_page_wrapper">

      <div class='header row'>
        <div class="header_wrapper col-lg-12">
          <%= content_tag :h1, @content_first.part_title if @content_first %>
        </div>
      </div>

      <%= render_partial_for_region(@content_first) %>


      <% if @placemarks.present? %>
        <div class='map_page_wrapper'>
          <div class="col-lg-4 layers col-md-4">
            <ul class='layers_list'>
              <li class='<%= @map_layer.parent.slug %>'>
                <%= link_to @map_layer.parent.title, map_layers_path(:map_layer => @map_layer.parent.slug) %>

                <ul>
                  <li class="<%= @map_layer.slug %>">
                    <%= link_to @map_layer.title, send("#{@map_layer.slug.underscore}_path", :map_layer => @map_layer.slug) %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>

          <div class="map_wrapper col-lg-8" data-latitude='58.62889684478054' data-longitude='82.06246307966687'>
            <div class="map"></div>
            <p> Для уточнения места расположения объекта увеличьте масштаб карты </p>
          </div>

          <div class="row placemark_list">
            <table class="table table-striped table-hover visible-xs visible-sm">
              <% @placemarks.each do |placemark| %>
                <% placemark.addresses.each_with_index do |address, index| %>
                  <tr class="placemark_list_item <%= index !=0 ? 'hidden' : '' %>" data-latitude=<%= address.latitude %> data-longitude=<%= address.longitude %> data-icon=<%= layer_icon(placemark.map_layer) %> data-title="<%= placemark.title %>" data-description="<%= placemark.description %>" data-logotype=<%= placemark_logotype(placemark) %>>
                    <td>
                      <%= image_tag layer_icon(placemark.map_layer) %>
                    </td>
                    <td>
                      <%= placemark.title %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          </div>
        </div>
      <% end %>

      <%= render_partial_for_region(@content_second) %>

      <%= render_partial_for_region(@content_third) %>

      <%= render_partial_for_region(@content_fourth) %>

    </div>

    <% if @content_navigation %>
      <div class='content_nav noindex col-lg-3 col-md-3 col-sm-4 hidden-xs'>
        <%= content_tag :div, render("regions/#{@content_navigation.type.underscore}", :object => @content_navigation.content), :class => 'navigation' if @content_navigation %>
      </div>
    <% end %>

  </div>
<% end %>