config/routes.rb
Rails.application.routes.draw do
  # Redirect majestic seo bot to main page
  get '/ru/press-tsentr/novosti/v-rossii/prosmotr_novosti/-/:id', to: redirect('/404'), id: /.+http:\/ria\.ru\/nano_news\/20120222\/572000474\.html/

  devise_for :users, controllers: { invitations: 'manage/invitations' }

  devise_scope :user do
    get 'manage/invitations', to: 'manage/invitations#index'
  end

  namespace :manage do
    resource :user, only: [:edit, :update]
    resources :map_layers,  except: [:show]
    resources :placemarks,  except: [:index, :show]
    resources :permissions, except: [:show, :edit, :update]
    resources :events,      except: [:show]

    root to: 'map_layers#index'
  end

  namespace :workplace do
    resources :documents do
      get 'tags_list', on: :collection
      get 'participants_list', on: :collection
      get 'related_documents', on: :collection
    end

    resources :user_tags

    root to: 'documents#index'
  end

  get 'ru/inotomsk/ob-ekty'          => 'map_layers#index', :as => 'map_layers'
  get 'ru/dorozhnaya-karta'          => 'road_map#index',   :as => 'road_map'

  %w(
    peredovoe-proizvodstvo
    nauka-i-obrazovanie
    umnyy-i-udobnyy-gorod
    innovatsii-i-noviy-biznes
    delovaya-sreda
  ).each do |item|
    get "ru/#{item}" => 'directions#show', :defaults => { slug: item }, :as => item.underscore
  end

  %w(
    advanced-industry
    science-and-education
    technological-innovations-new-businesses
    smart-and-handy-city
    business-environment
  ).each do |item|
    get "en/#{item}" => 'directions#show', :defaults => { slug: item }, :as => item.underscore
  end

  # peredovoe proizvodsto
  %w(
    peredovoe-proizvodstvo/neftehimicheskiy-klaster
    peredovoe-proizvodstvo/klaster_yadernyh_tekhnologiy
    peredovoe-proizvodstvo/industrialnyy-park
    peredovoe-proizvodstvo/klaster-farmatsevtiki-medtehniki-i-it
    peredovoe-proizvodstvo/klaster-smart-technologiestomsk
    peredovoe-proizvodstvo/lesopromyshlennyy-klaster
    peredovoe-proizvodstvo/klaster-vozobnovlyaemyh-prirodnyh-resursov
    peredovoe-proizvodstvo/klaster-trudnoizvlekaemyh-prirod-resursov

    nauka-i-obrazovanie/nauchno-obrazovatelnyy-park
    nauka-i-obrazovanie/uchastie-v-federalnyh-initsiativah
    nauka-i-obrazovanie/tomskiy-natsionalnyy-issledovatelskiy-meditsinskiy-tsentr
    nauka-i-obrazovanie/detskiy-tehnopark-kvantorium
    nauka-i-obrazovanie/alyans-translyatsionnoy-meditsiny

    innovatsii-i-noviy-biznes/osobaya-ekonomicheskaya-zona
    innovatsii-i-noviy-biznes/poyas-innovatsionnyh-kompaniy

    umnyy-i-udobnyy-gorod/tomskaya-aglomeratsiya
    umnyy-i-udobnyy-gorod/tomskie-naberezhnye
    umnyy-i-udobnyy-gorod/meditsinskiy-park
    umnyy-i-udobnyy-gorod/istoriko-kulturnyy-park
    umnyy-i-udobnyy-gorod/sportivnyy-park
    umnyy-i-udobnyy-gorod/transportnaya-infrastruktura

  ).each do |item|
    get "ru/#{item}" => 'subdirections#show', :defaults => { slug: item.split('/').last }, :as => item.split('/').last.underscore
  end

  get 'en/road-map' => 'road_map#index'

  get 'files/:id/download' => 'workplace/documents#download', as: :download

  get '/(*path)', to: 'main#index'
  root to: 'main#index'
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :title, :date_on, :number, :kind, :tags, :file, :tag_list, :annotation,
                  :related_documents_attributes, :map_layer_ids, :event_ids, :placemark_ids,
                  :participants, :participant_list

  has_many :related_documents,   dependent: :destroy
  has_many :documents, dependent: :destroy, foreign_key: 'related_document_id', class_name: 'RelatedDocument'
  has_many :document_map_layers, dependent: :destroy
  has_many :children, through: :related_documents, class_name: 'Document'
  has_many :document_map_placemarks, dependent: :destroy
  has_many :document_events, dependent: :destroy

  has_many :parents, through: :documents, class_name: 'Document'
  has_many :map_layers, through: :document_map_layers
  has_many :placemarks, through: :document_map_placemarks
  has_many :events, through: :document_events

  scope :ordered, -> { order(date_on: :desc) }

  accepts_nested_attributes_for :related_documents, allow_destroy: true

  validates_presence_of :title, :date_on, :kind, :file

  acts_as_taggable_on :tags, :participants

  after_create :notify_users

  extend Enumerize

  enumerize :kind, in: [
    :rept,                   # доклад
    :report,                 # отчет
    :letter,                 # письмо
    :agenda,                 # повестка
    :assignment,             # поручение
    :decree_by_government,   # постановление Правительства Российской Федерации
    :order,                  # приказ
    :protocol,               # протокол
    :disposal_by_deputy,     # распоряжение Губернатора Томской области
    :disposal_by_government, # распоряжение Правительства Российской Федерации
    :approved_by_deputy,     # утвержден заместителем Губернатора Томской области
  ], prefix: true

  normalize :title, :number

  has_attached_file :file, path: ':rails_root/files/:class/:id_partition/:filename',
                           url: '/files/:id/download',
                           preserve_files: true
  validates_attachment_presence :file
  do_not_validate_attachment_file_type :file
  before_post_process :rename_file
  validates_uniqueness_of :file_fingerprint, message: 'Данный файл уже был загружен ранее'

  def related_documents_objects
    related_documents.includes(:documents)
  end

  def full_title
    [
      title,
      'от',
      I18n.l(date_on),
      %(№#{number})
    ].join(' ')
  end

  def notify_users
    users = UserTag.where(tag: tag_list).map(&:user)
    users << UserMapLayer.where(map_layer: map_layers.pluck(:title)).map(&:user)

    users.flatten.uniq.each do |user|
      DocumentsMailer.send_notify(user, self).deliver_later
    end
  end

  private

  def rename_file
    filename = Russian.translit(File.basename(file_file_name, '.*').mb_chars.downcase).parameterize('-').tr('_', '-')
    extension = Russian.translit(File.extname(file_file_name).mb_chars.downcase).parameterize('-')
    file.instance_write :file_name, "#{filename.capitalize}.#{extension}"
  end
end

# == Schema Information
#
# Table name: documents
#
#  id                :integer          not null, primary key
#  title             :string
#  date_on           :date
#  tags              :text
#  kind              :string
#  file_file_name    :string
#  file_content_type :string
#  file_file_size    :integer
#  file_updated_at   :datetime
#  file_url          :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  file_fingerprint  :string
#  number            :string
#  annotation        :text
#  participants      :text
#

app/controllers/workplace/application_controller.rb
class Workplace::ApplicationController < ApplicationController
  before_action :authenticate_user!

  layout 'devise'

  respond_to :html

  rescue_from CanCan::AccessDenied do
    redirect_to root_path
  end
end

app/controllers/workplace/documents_controller.rb
module Workplace
  class DocumentsController < Workplace::ApplicationController
    load_and_authorize_resource

    before_filter :find_document, except: [:index, :new, :create, :tags_list, :participants_list, :related_documents]

    helper_method :search_params

    def index
      @documents = if params[:search]
                     DocumentsSearcher.new(params[:search].merge(page: params[:page], per_page: per_page)).search
                   else
                     Document.preload(:map_layers, :tags).ordered.page(page).per(per_page)
                   end
    end

    def show
      @document = Document.find(params[:id])
    end

    def new
      @document = Document.new
    end

    def create
      @document = Document.create(params[:document])

      respond_with @document, location: -> { workplace_document_path(@document) }
    end

    def edit
    end

    def update
      @document.update(params[:document])

      respond_with @document, location: -> { workplace_document_path @document }
    end

    def destroy
      @document.destroy

      redirect_to workplace_documents_path
    end

    def download
      send_file @document.file.path,
                filename: @document.file_file_name,
                type: @document.file_content_type,
                disposition: 'attachment'
    end

    %w(tags participants).each do |method_name|
      define_method %(#{method_name}_list) do
        tag_list = Document
                   .tag_counts_on(method_name.to_sym)
                   .map(&:name)
                   .sort
                   .select { |s| s.match(/#{Regexp.quote(params[:term])}/i) }

        render(text: tag_list.to_json) && return
      end
    end

    def related_documents
      docs = Document
             .where("title ilike ? or number ilike ? or to_char(date_on, 'DD.MM.YYYY') ilike ?", "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%")
             .where.not(id: params[:current])
      json = docs.map { |doc| { id: doc.id, label: doc.full_title, value: doc.title } }

      render json: json.to_json
    end

    def search_params
      Hashie::Mash.new params[:search]
    end

    private

    def find_document
      @document = Document.find(params[:id])
    end

    def page
      params[:page] || 1
    end

    def per_page
      50
    end
  end
end

app/controllers/workplace/user_tags_controller.rb
module Workplace
  class UserTagsController < Workplace::ApplicationController
    authorize_resource

    before_action :find_user, only: [:show, :update]

    def index
      @users = User.all
    end

    def update
      @user.user_tags.where(tag: @user.user_tags.pluck(:tag) - params[:user][:tags]).map(&:destroy)
      @user.user_map_layers.where(map_layer: @user.user_map_layers.pluck(:map_layer) - params[:user][:user_map_layers]).map(&:destroy)

      params[:user][:tags].each do |tag|
        @user.user_tags.create tag: tag
      end

      params[:user][:user_map_layers].each do |map_layer|
        @user.user_map_layers.create map_layer: map_layer
      end

      redirect_to workplace_user_tag_path(@user)
    end

    private

    def find_user
      @user = User.find(params[:id])
    end
  end
end

app/views/workplace/documents/_document.html.erb
<div class='well'>
  <%= link_to workplace_document_path(document) do %>
    <h2>
      <%= document.title %> от <%= I18n.l document.date_on %>
      <small><%= %(№#{document.number}) if document.number? %></small>
    </h2>

  <% end %>

  <% if document.tag_list.present? %>
    <p>
      <strong>Тэги</strong>
      <%=
        document.tag_list.map { |tag| content_tag(:span, link_to(tag, workplace_documents_path(search: { tags: [tag]  })), class: 'label label-primary') }
          .join(' ').html_safe
        %>
    </p>
  <% end %>

  <% if document.participant_list.present? %>
    <p>
      <strong>Участники</strong>
      <%=
        document.participant_list.map { |participant| content_tag(:span, link_to(participant, workplace_documents_path(search: { participants: [participant]  })),
                                                                  class: 'label label-primary') }
          .join(' ').html_safe
        %>
    </p>
  <% end %>

  <% if document.map_layers.present? %>
    <p>
      <strong>Кластер / Парк</strong>
      <%=
        document.map_layers.map { |map_layer| content_tag(:span, link_to(map_layer.title, workplace_documents_path(search: { map_layers: [map_layer.id]  })),
                                                                  class: 'label label-primary') }
          .join(' ').html_safe
        %>
    </p>
  <% end %>

  <% if document.events.present? %>
    <p>
      <strong>Мероприятия дорожной карты</strong>
      <%=
        document.events.map { |event| content_tag(:span, link_to(event.number, workplace_documents_path(search: { events: [event.id]  })),
                                                                  class: 'label label-primary') }
          .join(' ').html_safe
        %>
    </p>
  <% end %>

  <% if document.placemarks.present? %>
    <p>
      <strong>Объекты</strong>
      <%=
        document.placemarks.map { |placemark| content_tag(:span, link_to(%(#{placemark.title} № #{placemark.filled_number}), workplace_documents_path(search: { placemarks: [placemark.id]  })),
                                                                  class: 'label label-primary') }
          .join(' ').html_safe
        %>
    </p>
  <% end %>
</div>

app/views/workplace/documents/_form.html.erb
<div class='container-fluid'>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-12'>
        <h1><%= @document.new_record? ? 'Добавление документа' : 'Редактирование документа' %>
      </div>

      <div class='col-xs-12 form_wrapper'>
        <%= simple_nested_form_for @document, url: [:workplace, @document] do |f| %>
          <%= f.input :title %>
          <%= f.input :annotation %>
          <%= f.input :date_on %>
          <%= f.input :number %>
          <%= f.input :kind %>
          <%= f.input :tag_list, input_html: { value: @document.tag_list.sort.join(', '), class: 'js-tags' } %>
          <%= f.input :participant_list, input_html: { value: @document.participant_list.sort.join(', '), class: 'js-participants' } %>

          <%= f.association :map_layers,
            as: :grouped_select, group_method: :last,
            label_method: :title, value_method: :id,
            collection: MapLayer.order('title').from_depth(1).group_by(&:root),
            input_html: { class: 'js-chosen', multiple: true } %>

          <%= f.association :events,
            as: :select,
            label_method: :title, value_method: :id,
            input_html: { class: 'js-chosen', multiple: true } %>

          <%= f.association :placemarks,
            as: :select,
            label_method: :title, value_method: :id,
            input_html: { class: 'js-chosen', multiple: true } %>

          <hr />

          <% if f.object.file.present? %>
            <p><%= link_to f.object.file_file_name, f.object.file.url %></p>
          <% end %>

          <%= f.input :file %>
          <% if @document.errors[:file_fingerprint].any? %>
            <p class='text-danger'><%= @document.errors[:file_fingerprint].join %></p>
          <% end %>

          <fieldset>
            <legend>Связанные документы</legend>
                <%= f.simple_fields_for :related_documents do |df| %>
                  <%= df.input :related_document_id, as: :hidden, input_html: { class: 'js-document-id' } %>
                  <%=
                    df.input :related_document_title,
                      input_html: {
                      value: df.object.try(:child).try(:title),
                      placeholder: 'Начните вводить название документа',
                      class: 'js-document-autocomplete',
                      data: { current: params[:id] }
                    }
                  %>

                <%= df.link_to_remove 'удалить' %>

            <% if df.object.errors[:related_document_id].any? %>
              <p class='text-danger'><%= df.object.errors[:related_document_id].join %></p>
            <% end %>
          <% end %>
        </fieldset>

        <p><%= f.link_to_add 'Добавить связанный документ', :related_documents %></p>

        <hr />

        <%= f.submit @document.new_record? ? 'Добавить' : 'Сохранить', class: 'btn btn-primary' %>

        <%= link_to 'Отмена', @document.new_record? ? workplace_documents_path : workplace_document_path(@document), class: 'btn btn-default' %>

        <% unless @document.new_record? %>
          <p class='pull-right'>
            <%= link_to 'Удалить', workplace_document_path(@document), method: :delete, :data => { :confirm => 'Вы уверены?' }, class: 'btn btn-warning' %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/workplace/documents/_parents_tree.html.erb
<% if @document.parents.present? %>
  <h4>Основания для этого документа</h4>

  <% recursive_parents(@document).each do |hash| %>
    <% if hash[:root].flatten.compact.present? %>
      <% hash[:root].each do |root_documents| %>
        <% root_documents.each do |root_document| %>
          <ul>
            <li>
              <%= link_to root_document.title, [:workplace, root_document] %>
              <ul>
                <% hash[:children].each do |child| %>
                  <li>
                    <%= link_to child.title, [:workplace, child] %>
                  </li>
                <% end %>

                <ul>
                  <li>
                    Этот документ
                  </li>
                </ul>
              </ul>
            </li>
          </ul>
        <% end %>
      <% end %>
    <% else %>
      <ul>
        <% hash[:children].each do |child| %>
          <li>
            <%= link_to child.title, [:workplace, child] %>
          </li>
        <% end %>

        <ul>
          <li>
            Этот документ
          </li>
        </ul>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/workplace/documents/_search_form.html.erb
<div class='row'>
  <div class='col-xs-12 form-wrapper'>
    <div class='col-xs-12'>
      <h3>Поиск</h3>
    </div>

    <%= simple_form_for :search, url: '', method: :get, wrapper: :inline_form do |f| %>
      <div class='col-xs-12'>
        <%= f.input :q,
          label: false,
          input_html: {
            placeholder: 'Поиск по названию документа',
            value: params[:search].try(:[], :q)
          }
        %>
      </div>

      <% if @documents.flat_map(&:tag_list).uniq.sort.present? %>
        <div class='col-xs-6'>
          <p>Выбор по тэгам</p>
          <%=
            f.input :tags,
              as: :select,
              label: 'Тэги',
              collection: @documents.flat_map(&:tag_list).uniq.sort,
              selected: params[:search].try(:[], :tags),
              input_html: { class: 'js-chosen', multiple: true }
            %>
        </div>
      <% end %>

      <% if @documents.flat_map(&:participant_list).uniq.sort %>
        <div class='col-xs-6'>
          <p>Выбор по участникам</p>
          <%=
            f.input :participants,
              as: :select,
              label: 'Участники',
              collection: @documents.flat_map(&:participant_list).uniq.sort,
              selected: params[:search].try(:[], :participants),
              input_html: { class: 'js-chosen', multiple: true }
            %>
        </div>
      <% end %>

      <% if @documents.flat_map(&:map_layers).uniq.sort %>
        <div class='col-xs-12'>
          <p>Кластер / Парк</p>
          <%=
            f.input :map_layers,
              as: :select,
              label: 'Кластер / Парк',
              collection: @documents.flat_map(&:map_layers).uniq.sort,
              label_method: :title,
              selected: params[:search].try(:[], :map_layers),
              input_html: { class: 'js-chosen', multiple: true  }
            %>
        </div>
      <% end %>

      <% if @documents.flat_map(&:events).uniq.sort %>
        <div class='col-xs-12'>
          <p>Выбор по мероприятиям дорожной карты</p>
          <%=
            f.input :events,
              as: :select,
              label: 'Номера мероприятий дорожной карты',
              collection: @documents.flat_map(&:events).uniq.sort,
              label_method: :filled_number,
              value_method: :id,
              selected: params[:search].try(:[], :events),
              input_html: { class: 'js-chosen', multiple: true  }
            %>
        </div>
      <% end %>

      <% if @documents.flat_map(&:placemarks).uniq.sort %>
        <div class='col-xs-12'>
          <p>Выбор по объектам</p>
          <%=
            f.input :placemarks,
              as: :select,
              label: 'Объекты',
              collection: @documents.flat_map(&:placemarks).uniq.sort,
              label_method: :full_title,
              value_method: :id,
              selected: params[:search].try(:[], :placemarks),
              input_html: { class: 'js-chosen', multiple: true  }
            %>
        </div>
      <% end %>

      <div class='col-xs-12'>
        <%= f.submit 'Искать', class: 'btn btn-primary' %>
        <%= link_to 'Очистить', [:workplace, :documents] %>
        <hr />
      </div>

      <div class='col-xs-12'>
        Найдено документов: <%= @documents.total_count %>
      </div>
    <% end %>
  </div>
</div>

app/views/workplace/documents/edit.html.erb
<%= render :partial => 'form' %>

app/views/workplace/documents/index.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <h1>Документы
      <%=
        link_to '+ Новый документ',
          new_workplace_document_path,
          :class => 'btn btn-success btn-sm js-tooltip',
          title: 'Добавить новый документ' if can?(:new, Document)
        %>
    </h1>
  </div>
</div>

<%= render 'search_form' %>

<br />

<div class='row'>
  <div class='col-xs-12'>
    <% if @documents.present? %>
      <% @documents.each do |document| %>
        <%= render document %>
      <% end %>
    <% else %>
      <p class='text-warning'>Ничего не найдено по вашему запросу, попробуйте изменить параметры поиска</p>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='col-xs-12'>
    <%= paginate @documents %>
  </div>
</div>

app/views/workplace/documents/new.html.erb
<%= render :partial => 'form' %>

app/views/workplace/documents/show.html.erb
<div class='container-fluid'>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-12'>
        <%= render 'parents_tree' %>
      </div>
    </div>

    <div class='row'>
      <div class='col-xs-12'>
        <div class='page-header'>
          <h1>
            <%= @document.title %> от <%= I18n.l(@document.date_on) %>
            <small>
              <%= %(№#{@document.number}) if @document.number? %>
            </small>

            <%= link_to edit_workplace_document_path(@document) do %>
              <span class='glyphicon glyphicon-pencil js-tooltip' title='Изменить'></span>
            <% end if can?(:edit, @document)%>
          </h1>
        </div>
      </div>
    </div>

    <div class='row'>
      <div class='col-xs-4'>

        <h4>Кластер / Парк</h4>
        <% if @document.map_layers.present? %>
          <ul>
            <% @document.map_layers.each do |map_layer| %>
              <li>
                <%= link_to map_layer.title, workplace_documents_path(search: { map_layers: map_layer.id }) %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>Не указан Кластер / Парк</p>
        <% end %>
      </div>

      <div class='col-xs-4'>
        <h4>Аннотация</h4>
        <p>
          <%= @document.annotation.presence || 'Нет аннотации' %>
        </p>
      </div>

      <div class='col-xs-4'>
        <h4>Тип документа</h4>
        <p><%= @document.kind_text %></p>
      </div>
    </div>

    <div class='row'>
      <div class='col-xs-4'>
        <h4>Тэги</h4>
        <ul>
          <% @document.tag_list.each do |tag| %>
            <li>
              <%= link_to tag, workplace_documents_path(search: { tags: [tag] }) %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class='col-xs-4'>
        <h4>Документ</h4>
        <p>
          <%= link_to @document.file.url do %>
            <%= @document.file_file_name %>

            <span class='glyphicon glyphicon-floppy-disk js-tooltip' title='Скачать'></span>
          <% end %>
        </p>
      </div>

      <div class='col-xs-4'>
        <h4>Документы во исполнение распоряжения, поручения, протокола / ответ на письмо / предложения по вопросу</h4>
        <p>
          <% if @document.children.present? %>
            <ul>
              <% @document.children.each do |child| %>
                <li>
                  <%= link_to  [:workplace, child] do %>
                    <%= child.title %> от <%= I18n.l(child.date_on) %>
                    <small>
                      <%= %(№#{child.number}) if child.number? %>
                    </small>
                  <% end %>
                </li>
              <% end %>
            </ul>
          <% else %>
            Нет документов
          <% end %>
        </p>

      </div>

    </div>

    <div class="row">
      <div class="col-xs-4">
        <h4>Участники</h4>
        <ul>
          <% @document.participant_list.each do |participant| %>
            <li>
              <%= link_to participant, workplace_documents_path(search: { participants: [participant] }) %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="col-xs-4">
        <h4>Мероприятия "Дорожной карты"</h4>
        <ul>
          <% @document.events.each do |event| %>
            <li>
              <%= link_to event.title, workplace_documents_path(search: { events: [event] }) %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="col-xs-4">
        <h4>Объекты</h4>
        <ul>
          <% @document.placemarks.each do |placemark| %>
            <li>
              <%= link_to placemark.full_title, workplace_documents_path(search: { placemarks: [placemark.id] }) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class='row'>
      <div class='col-xs-12'>
        <p>
          <%= link_to 'Назад к списку', workplace_documents_path, class: 'btn btn-default' %>
        </p>
      </div>
    </div>

  </div>
</div>